version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: memori-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: ["uvicorn", "memory_api:app", "--host", "0.0.0.0", "--port", "8000"]

  # Uncomment and configure if you have a frontend static server or separate frontend service
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: memori-frontend
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped
